<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Subtotal_total-row (1)</name>
   <tag></tag>
   <elementGuidId>51230970-ef45-4f66-90ae-df25a62a9128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='checkout']/div/div[2]/div[2]/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d880824f-d457-4f27-9d51-668ec0f068fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>total-row</value>
      <webElementGuid>81f80a80-7da6-4e98-a812-99f4ee27f4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Shipping:
                                Free
                            </value>
      <webElementGuid>eb34b707-e9fc-4e7b-877b-515979db7e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout&quot;)/div[@class=&quot;checkout-container&quot;]/div[@class=&quot;checkout-content&quot;]/div[@class=&quot;checkout-right&quot;]/div[@class=&quot;order-summary&quot;]/div[@class=&quot;order-totals&quot;]/div[@class=&quot;total-row&quot;]</value>
      <webElementGuid>9cca36c2-0d76-4a40-9c98-6d1882036e3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='checkout']/div/div[2]/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>28ed6ec1-224b-4641-bb71-8ba264f6799a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal:'])[1]/following::div[1]</value>
      <webElementGuid>772b2c3b-6fab-42c8-a641-e17aa4c8ff37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x1'])[1]/following::div[3]</value>
      <webElementGuid>ecbc8c51-8369-404d-9eb4-e123f4e14990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>de8f60e2-6a3e-4507-b8fd-72047bd41e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                Shipping:
                                Free
                            ' or . = '
                                Shipping:
                                Free
                            ')]</value>
      <webElementGuid>6830409a-331e-4bd3-8f52-f134e4ebed5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
