<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Subtotal_total-row</name>
   <tag></tag>
   <elementGuidId>36e53f4e-882f-4993-a1b7-7879fb413984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='checkout']/div/div[2]/div[2]/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef62ca15-5dc3-4ac7-b40d-0f7db345205b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>total-row</value>
      <webElementGuid>eddb870c-c1ff-4562-a4a0-ec7ac5b5e0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Shipping:
                                Free
                            </value>
      <webElementGuid>08d2023d-5bc7-4ac4-8f6c-d4c84b76788d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout&quot;)/div[@class=&quot;checkout-container&quot;]/div[@class=&quot;checkout-content&quot;]/div[@class=&quot;checkout-right&quot;]/div[@class=&quot;order-summary&quot;]/div[@class=&quot;order-totals&quot;]/div[@class=&quot;total-row&quot;]</value>
      <webElementGuid>5c360b44-28f9-42dd-913a-53c3361371db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='checkout']/div/div[2]/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>26f9f656-daf5-4316-96a7-8f4044f0de5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal:'])[1]/following::div[1]</value>
      <webElementGuid>5b2bdf1b-1198-4518-8b9b-f3d7a5c24f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x1'])[1]/following::div[3]</value>
      <webElementGuid>4622e225-8c39-412e-a32a-540c4839ac55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>9252ceb7-76c9-494b-853a-240ac23e3f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                Shipping:
                                Free
                            ' or . = '
                                Shipping:
                                Free
                            ')]</value>
      <webElementGuid>04f0a565-e2c7-44b4-a5e4-b0b9272ea4b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
