<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__productPrice</name>
   <tag></tag>
   <elementGuidId>257b0945-64d8-42db-aa65-2fe9bae3783f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#productPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='productPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0225db64-04fd-4ae8-969f-ee101d457b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>34572b72-e0d9-496f-8c32-de189297c3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input</value>
      <webElementGuid>78de5cef-4091-4779-b2a3-d5c35dee0e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productPrice</value>
      <webElementGuid>53cc3afb-49d0-473e-9b2c-d7a3abc8535f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unit_price</value>
      <webElementGuid>445520a6-d2b0-450b-a7fc-662febebf26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>96b2d1ef-c55d-4cb5-a3c7-f82163836aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>9e72702e-0ac4-4889-8a49-6751aa2f1161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productPrice&quot;)</value>
      <webElementGuid>d84446bb-ea65-4056-bdef-19f3a4373593</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='productPrice']</value>
      <webElementGuid>2d03d69a-df47-43fe-aa59-2dcf1dfa053d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='productForm']/div[3]/div/input</value>
      <webElementGuid>d81f4c9d-c5e6-4a45-8f7b-18609ace9a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>f5b5e03f-fce4-4eea-bce9-499d6dc1bc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'productPrice' and @name = 'unit_price']</value>
      <webElementGuid>5638a42a-ed1d-4a24-97de-55507ed53113</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
