<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__supplierSelect (2)</name>
   <tag></tag>
   <elementGuidId>39d28f4e-1637-44be-bb66-f7df9ef37ff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#supplierSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='supplierSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>37ea7c44-b62e-4a4b-b032-db751794e77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>828136bd-cff5-4f91-afe5-2e40fa7dde44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>supplierSelect</value>
      <webElementGuid>ba0e8d25-6e9e-4ffa-9250-ddecb818b91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>supplier_id</value>
      <webElementGuid>d43a64ad-35a9-4166-9f70-44696aca8fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Choose Supplier
                            Canon
                            Sony
                            Nikon
                            Fujifilm
                            Manfrotto
                        </value>
      <webElementGuid>ccb4f239-3ca4-4d0e-a9a0-f27f3da12f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplierSelect&quot;)</value>
      <webElementGuid>4a5bc814-dbe1-4dee-9fc2-fd123eb0c144</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='supplierSelect']</value>
      <webElementGuid>f1f69a6f-0764-4704-8c88-09a7022a65a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='productForm']/div[2]/div[2]/select</value>
      <webElementGuid>296ba1e3-035a-4f4c-ba1a-acafcd7cc8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>a694de17-a15a-4f41-a4d0-641fda1d36a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::select[1]</value>
      <webElementGuid>c140f010-2c93-46b7-b43e-616e6acd8ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/select</value>
      <webElementGuid>e3ae5ebd-ed8b-4495-8806-f962a98b6605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'supplierSelect' and @name = 'supplier_id' and (text() = '
                            Choose Supplier
                            Canon
                            Sony
                            Nikon
                            Fujifilm
                            Manfrotto
                        ' or . = '
                            Choose Supplier
                            Canon
                            Sony
                            Nikon
                            Fujifilm
                            Manfrotto
                        ')]</value>
      <webElementGuid>c103e2eb-98a4-4745-9ccb-f5df57f01e1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
