<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__categorySelect (2)</name>
   <tag></tag>
   <elementGuidId>1c2b4df0-648c-4301-8318-6e73b22777c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#categorySelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='categorySelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bb29a627-db74-4b6f-a4bd-8c47961781eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>11855ad5-7ec6-437f-932e-1e70466c3bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categorySelect</value>
      <webElementGuid>61db222c-77f7-4195-a331-890d041ffdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category_id</value>
      <webElementGuid>4d95beee-d09d-4506-ba4e-db73a6494c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Choose Category
                            Camera
                            Gear
                            Lens
                        </value>
      <webElementGuid>5b8163ed-5aca-4164-8278-763b48d643f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categorySelect&quot;)</value>
      <webElementGuid>8161f5aa-bd50-4f74-b219-3f097caf5a4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='categorySelect']</value>
      <webElementGuid>ade5a895-8b21-435a-8889-34e4ab9ce650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='productForm']/div[2]/div/select</value>
      <webElementGuid>1caff341-b4ac-469a-a9fa-4ec453166d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>7269c04a-d1be-428b-a06f-d5fcaf10da6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>a0ca2b51-374b-4807-b14b-d94f03ecfffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>02be640e-90c5-48b0-b1b8-46ccfd26407c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'categorySelect' and @name = 'category_id' and (text() = '
                            Choose Category
                            Camera
                            Gear
                            Lens
                        ' or . = '
                            Choose Category
                            Camera
                            Gear
                            Lens
                        ')]</value>
      <webElementGuid>74abc83d-3e5a-4174-9ac3-c9e898861884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
