<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__categorySelect (1)</name>
   <tag></tag>
   <elementGuidId>213276a4-10cd-479c-9d76-07113c427722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#categorySelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='categorySelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>36b33c51-b265-4164-8f9e-4f7a04fb1d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>2f2e6f4e-c365-43ec-a458-1d355af1a31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categorySelect</value>
      <webElementGuid>63b85691-59d3-4ed6-9d2a-84316387775b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category_id</value>
      <webElementGuid>4909e8a9-3dab-4af4-97f7-056b5dbd82b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Choose Category
                            Camera
                            Gear
                            Lens
                        </value>
      <webElementGuid>a83d47e3-9c7d-4313-a5d9-b1130a80c64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categorySelect&quot;)</value>
      <webElementGuid>b4bafa66-4315-4eb3-ac6c-16fd759fd0c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='categorySelect']</value>
      <webElementGuid>60fd403d-fabb-4e36-8adf-32765f1cfdaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='productForm']/div[2]/div/select</value>
      <webElementGuid>89e1ab8f-686f-4937-ad48-6d099e53e39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>d85fd85b-26df-426b-963e-40a39326d546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>117e50e8-f30c-4201-af7f-dc72ea69ebdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>8128017c-748c-431d-a7e7-ac8d2e1f7f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'categorySelect' and @name = 'category_id' and (text() = '
                            Choose Category
                            Camera
                            Gear
                            Lens
                        ' or . = '
                            Choose Category
                            Camera
                            Gear
                            Lens
                        ')]</value>
      <webElementGuid>58f0677d-a038-44e4-81ee-f5c957c03a40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
