<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__categorySelect (3)</name>
   <tag></tag>
   <elementGuidId>e847be78-a519-46fd-b3bf-35e667ed3987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#categorySelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='categorySelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c5c6a840-076b-40dd-93bb-473f0c23a54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>b22dbffa-ab91-4f00-b347-b78e2ef6c794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categorySelect</value>
      <webElementGuid>7c54dae5-d868-4c6d-94e5-53f85837f329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category_id</value>
      <webElementGuid>8c66e94f-fd7f-45dc-89ba-916ad0244703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Choose Category
                            Camera
                            Gear
                            Lens
                        </value>
      <webElementGuid>fe813a79-6a01-494e-a37c-d6edac7af093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categorySelect&quot;)</value>
      <webElementGuid>ce4ff8f2-0139-4d4e-983f-bc78f0db1056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='categorySelect']</value>
      <webElementGuid>fec08ceb-b68f-402d-bf1f-a5e90c707459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='productForm']/div[2]/div/select</value>
      <webElementGuid>f7d63456-e49a-45ca-a341-b65864fa57a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>e9e15937-41b8-4f64-a181-3c4cec2eaa6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>f846f521-70dd-43e2-a52b-b0d83ddd0b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>34e3f18b-5fc3-4ca1-b467-f9469da2a792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'categorySelect' and @name = 'category_id' and (text() = '
                            Choose Category
                            Camera
                            Gear
                            Lens
                        ' or . = '
                            Choose Category
                            Camera
                            Gear
                            Lens
                        ')]</value>
      <webElementGuid>eb986d4a-c012-4618-b071-b36184d689ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
