<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__supplierSelect (1)</name>
   <tag></tag>
   <elementGuidId>4fb13a75-3f9a-4609-9efc-02fc4e6597e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#supplierSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='supplierSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0a4bc4af-5f29-42ec-9376-58cc5d61747c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>3ff97462-da86-4d2e-9533-894ec691f7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>supplierSelect</value>
      <webElementGuid>3b047b4d-ed94-4e3c-a24f-a2a5a9f6c220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>supplier_id</value>
      <webElementGuid>e6f50ee0-03da-4fff-94fe-51aab6998472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Choose Supplier
                            Canon
                            Sony
                            Nikon
                            Fujifilm
                            Manfrotto
                        </value>
      <webElementGuid>b2814828-1792-45a8-ae90-31e36bcf7f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplierSelect&quot;)</value>
      <webElementGuid>1f9a3441-78d9-4cb9-a6cb-66cdd41b0d8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='supplierSelect']</value>
      <webElementGuid>a12d324e-2a9a-4d42-8a85-1535e156cd8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='productForm']/div[2]/div[2]/select</value>
      <webElementGuid>e4f79aa8-aaee-40fb-8bc7-7e9b569433db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>e70b01ee-c239-4dc4-89e4-aebf08312f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::select[1]</value>
      <webElementGuid>9a7497d3-bc77-4f66-8524-fbe9df899493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/select</value>
      <webElementGuid>6d0bcba7-5dca-45e8-bfae-6def0855afcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'supplierSelect' and @name = 'supplier_id' and (text() = '
                            Choose Supplier
                            Canon
                            Sony
                            Nikon
                            Fujifilm
                            Manfrotto
                        ' or . = '
                            Choose Supplier
                            Canon
                            Sony
                            Nikon
                            Fujifilm
                            Manfrotto
                        ')]</value>
      <webElementGuid>0c2ebea7-66d0-46a3-a9c8-6f554d5f3c78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
