<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_productDescription</name>
   <tag></tag>
   <elementGuidId>cd5a4851-63de-485f-bef7-aaa3e577a0e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#productDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='productDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6661566b-54e8-4f55-95f8-b643240f7532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-textarea</value>
      <webElementGuid>81aca834-cefb-440e-856c-67e9135977f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productDescription</value>
      <webElementGuid>81428128-c033-421b-90c3-da440c76c447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>3c3f26bf-1b35-490d-8302-ebd1a4e49e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>21d8f649-61ae-4653-8a0e-f26e403f6657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productDescription&quot;)</value>
      <webElementGuid>c0723f95-4d3d-411a-9bb9-72153fa2626f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='productDescription']</value>
      <webElementGuid>23c47452-b861-4dc0-b728-1ebe2831ab9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='productForm']/div[4]/textarea</value>
      <webElementGuid>37ff11f9-0f17-4099-af18-4d7da6cf63e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3d187db3-7550-4912-be83-228ecbfeb7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'productDescription' and @name = 'description']</value>
      <webElementGuid>cded0451-3e77-436a-95d2-7f7ce0bf2e12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
