<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Contact_fas fa-shopping-cart (9)</name>
   <tag></tag>
   <elementGuidId>d815a5ff-c802-4467-8d1b-d998ebacdb39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-shopping-cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='lg-cart']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d551d670-7d6c-4402-a106-5545c5d6731c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-shopping-cart</value>
      <webElementGuid>c488764e-3116-4b34-9e89-3cff6831fd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lg-cart&quot;)/a[1]/i[@class=&quot;fas fa-shopping-cart&quot;]</value>
      <webElementGuid>ca78e8ff-433c-463d-b268-58eafb0e8e90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='lg-cart']/a/i</value>
      <webElementGuid>e72931ba-a9c1-4077-a72e-9efbe64a32ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>ae492297-f27f-49e1-8350-5f72511527e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
