<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Contact_fas fa-shopping-cart (1)</name>
   <tag></tag>
   <elementGuidId>affe5bd5-d3fa-4ea5-851d-379169ef3135</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='lg-cart']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-shopping-cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9024d782-0f07-41b8-a015-ce256c7ffe9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-shopping-cart</value>
      <webElementGuid>ac26418c-f3a9-4673-915a-dd349b81e20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lg-cart&quot;)/a[1]/i[@class=&quot;fas fa-shopping-cart&quot;]</value>
      <webElementGuid>725dda12-c6b0-4b13-b879-f1b6d0396ef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='lg-cart']/a/i</value>
      <webElementGuid>4dd7c16a-76f1-4742-a3a1-e7866a8f2497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>0d2d8e04-f658-46b9-a00d-52ca27de5ddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
