<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_My nh k thut s Sony ZV-E10_far fa-cart-plus cart</name>
   <tag></tag>
   <elementGuidId>c6ec0507-ce0d-4528-b86b-4e803549d0ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-list']/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.far.fa-cart-plus.cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a0e5d1b9-61bb-4e29-9da6-b1540606f708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>far fa-cart-plus cart</value>
      <webElementGuid>9c868f04-36e3-454d-b8ed-59ebb4d24e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-list&quot;)/div[@class=&quot;pro&quot;]/a[1]/i[@class=&quot;far fa-cart-plus cart&quot;]</value>
      <webElementGuid>6b2c6712-5c4c-4199-a9bf-60c6aefad1f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-list']/div/a/i</value>
      <webElementGuid>64c96c95-ca74-49f4-9cc3-2be3224bbf55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/a/i</value>
      <webElementGuid>a0aa7fe8-52a1-4dea-9c8a-908578a46296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
