<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_My nh k thut s Sony ZV-E10_far fa-cart-plus cart (7)</name>
   <tag></tag>
   <elementGuidId>fe6b06ae-55ec-46e0-9a66-2c3f44811c90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.far.fa-cart-plus.cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-list']/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>04f20487-d956-48cb-940c-d67587a984cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>far fa-cart-plus cart</value>
      <webElementGuid>5e033a5c-31dd-4a5f-953b-a6275f1ca7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-list&quot;)/div[@class=&quot;pro&quot;]/a[1]/i[@class=&quot;far fa-cart-plus cart&quot;]</value>
      <webElementGuid>75564408-2a6f-4b57-9898-02f952764ab9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-list']/div/a/i</value>
      <webElementGuid>7de6fa04-b06e-4253-9c1a-013ec939ff86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/a/i</value>
      <webElementGuid>aa121e24-cc68-4c85-b94d-f3c7bbc24047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
