<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Wait for payment_page-btn_1 (1)</name>
   <tag></tag>
   <elementGuidId>fc23964d-6a37-44d0-875a-2c2889edaaa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.page-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='loadOrders(1);return false;']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa746b4b-e214-4e92-975d-ffacfb7ddd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-btn</value>
      <webElementGuid>49c8b4c2-52bd-4f9b-b98e-0f492a94a04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>06a5d8e5-0f35-41e8-a81e-d9fefabc2659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>loadOrders(1);return false;</value>
      <webElementGuid>e136edd4-04ea-46c8-bc33-dd9ac7f50e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>‹</value>
      <webElementGuid>f846cff4-19ae-4980-b50c-44bd068e6d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagination&quot;)/a[@class=&quot;page-btn&quot;]</value>
      <webElementGuid>817204a1-6893-4dd8-a1b9-120187e350e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='loadOrders(1);return false;']</value>
      <webElementGuid>df291f38-4b18-4345-a3e3-8cf6a8a88b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagination']/a</value>
      <webElementGuid>7e9235b9-87d1-453c-a4eb-26d6435ffbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'‹')]</value>
      <webElementGuid>8533b9e5-9f6f-4d66-ba87-1adac2b28061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wait for payment'])[5]/following::a[1]</value>
      <webElementGuid>79d477ce-8d20-406e-a94a-f69ea7686151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash On Delivery'])[5]/following::a[1]</value>
      <webElementGuid>ea88fdd4-f2b6-4107-86ce-780bd1372985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạo đơn hàng mới'])[1]/preceding::a[3]</value>
      <webElementGuid>57157d0e-be4d-4518-a32a-fbe04d1b7179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::a[3]</value>
      <webElementGuid>f902a815-3d83-4b54-a45a-39bbaffb6bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='‹']/parent::*</value>
      <webElementGuid>29e14a95-2b45-418a-b587-cec159cbe421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>5081e0b2-c8af-4990-ab7b-8d62a91504c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>2f7320d7-5424-49c9-87ab-08abe22969c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '‹' or . = '‹')]</value>
      <webElementGuid>a562ded2-25f9-4d81-995e-2f67dcf91d20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
