<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Khch hng_customer_search (1)</name>
   <tag></tag>
   <elementGuidId>7cf921dd-aa37-4099-a33f-4e394e08e4c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc5cc1a9-7783-417c-9a09-6618b6dede8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33cab91f-2d55-405e-ba41-9781900149d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input</value>
      <webElementGuid>393f2755-5034-4e5c-a65c-2092a710c27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_search</value>
      <webElementGuid>6f6df1a9-3779-4487-9712-a0107e294ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm kiếm khách hàng (ID, Username, Email)...</value>
      <webElementGuid>0611bef6-e149-4b52-8d7b-ee9382a4ae90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>searchCustomer(this.value)</value>
      <webElementGuid>3c82e791-c206-4494-a93b-a471a776752e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_search&quot;)</value>
      <webElementGuid>d7ffb73f-35d2-4870-a961-5763b76b4968</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_search']</value>
      <webElementGuid>af6c4045-cc58-4e45-afdb-2efa9cddbde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='orderForm']/div/div/div/input</value>
      <webElementGuid>b22aed4e-1ec9-4230-9bb5-13e9cf3b8514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>5b95febf-c31b-48f9-b338-4a85d3ca6fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'customer_search' and @placeholder = 'Tìm kiếm khách hàng (ID, Username, Email)...']</value>
      <webElementGuid>ff4644bd-a2b5-4174-bee7-ee412189bd80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
