<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Khch hng_customer_search (3)</name>
   <tag></tag>
   <elementGuidId>c344fd38-ad96-40d3-8e5d-6990a865a9c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d09ce522-bc94-4274-8cda-3a48290b0c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d428865-6ed7-46c2-9a76-64671d5551d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input</value>
      <webElementGuid>0d83d4b1-089a-49d6-b50a-265344d34778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_search</value>
      <webElementGuid>dca825ba-8af9-44be-acb7-147cf3ef179e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm kiếm khách hàng (ID, Username, Email)...</value>
      <webElementGuid>5f88e05e-c3c6-427f-829b-bd6ddcaf4a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>searchCustomer(this.value)</value>
      <webElementGuid>130662c9-5d5f-43fa-abbe-1e77f0b37db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_search&quot;)</value>
      <webElementGuid>b26381d7-7620-429f-93d0-a2b5be3a9b97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_search']</value>
      <webElementGuid>2459d241-3c8b-4d5d-86b8-b586f5813585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='orderForm']/div/div/div/input</value>
      <webElementGuid>ab0ba30f-0ba6-4ba7-9afb-fc482912faeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>534a6589-9b97-4702-9bcc-95a5f5b90eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'customer_search' and @placeholder = 'Tìm kiếm khách hàng (ID, Username, Email)...']</value>
      <webElementGuid>b49191bb-000d-462c-a941-e4809048b794</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
