<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Khch hng_customer_search</name>
   <tag></tag>
   <elementGuidId>abcc1b59-6df9-4694-91dd-fadc9f06cff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b550e58-1ecd-4e7a-b6c2-fd323515b953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f807970-7d61-41aa-99e5-1009424b3b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input</value>
      <webElementGuid>caee7ad3-d218-4702-9df4-dc8c3cf1986c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_search</value>
      <webElementGuid>df1d194d-15d4-4997-ba0a-3eefc7bb449d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm kiếm khách hàng (ID, Username, Email)...</value>
      <webElementGuid>279674e3-0fd2-4657-8fbf-2cca633cc025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>searchCustomer(this.value)</value>
      <webElementGuid>e4a40623-138e-4a46-b0aa-7fd3b6efafed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_search&quot;)</value>
      <webElementGuid>d044290f-2ffe-4ee6-92fe-44515b2732e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_search']</value>
      <webElementGuid>68821faf-888f-4436-b00e-f3dfa560fa50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='orderForm']/div/div/div/input</value>
      <webElementGuid>bb4897d9-ead9-4590-968a-5aa14d3b4791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>c80fd40c-9044-4237-b814-32698821a43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'customer_search' and @placeholder = 'Tìm kiếm khách hàng (ID, Username, Email)...']</value>
      <webElementGuid>24a07760-89c8-4e32-94f8-0553ec380f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
