<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong</name>
   <tag></tag>
   <elementGuidId>afb124e6-9b7b-4a7b-9d0a-653d8ae100bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='customer_results']/div/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>73f73276-c686-44bd-a119-8664fd10da6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hungtran</value>
      <webElementGuid>aa46f65b-093d-4e36-9ca6-a474a7cdb43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_results&quot;)/div[1]/strong[1]</value>
      <webElementGuid>5b5575ef-57b2-40f1-8005-2f26aaa55f98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_results']/div/strong</value>
      <webElementGuid>b0e90751-fb82-4dbd-8741-3f2d299b0665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khách hàng'])[1]/following::strong[1]</value>
      <webElementGuid>8267e9e7-fb32-46f6-842d-b97df0802e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hungstar89@gmail.com'])[1]/preceding::strong[1]</value>
      <webElementGuid>c0eea066-3a09-41e9-96bd-e9c6d5a66568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Để trống nếu là khách vãng lai'])[1]/preceding::strong[1]</value>
      <webElementGuid>ea46319a-e750-45c1-bf3c-66867fff4c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='hungtran']/parent::*</value>
      <webElementGuid>e40c7a29-7de4-454a-a9f1-e064bbcbf88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>544ff1e2-9c98-4d0b-9919-84c81d10be45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'hungtran' or . = 'hungtran')]</value>
      <webElementGuid>3ba6f47c-7a74-4e11-8fb5-54185565068e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
