<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Successemails_performance-button</name>
   <tag></tag>
   <elementGuidId>ec2cd119-0504-4f6e-b95d-14996b69cf11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='emailForm']/div[4]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.performance-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24367cf6-a70e-439e-9129-d351aedbca9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost/CamNest/admin/emailPerformance</value>
      <webElementGuid>de4c815f-8dc6-48ee-9945-b0e4133a0f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>performance-button</value>
      <webElementGuid>be64da4c-305d-48c6-ad0f-ce946ffe9158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                 Performance Analyzer
              </value>
      <webElementGuid>682a7ea5-e781-45f0-8915-4f532a2ba0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailForm&quot;)/div[@class=&quot;form-button-group&quot;]/div[@class=&quot;performance-container&quot;]/a[@class=&quot;performance-button&quot;]</value>
      <webElementGuid>c1291ce8-f42f-46be-9cd5-3c0e34d691ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='emailForm']/div[4]/div[2]/a</value>
      <webElementGuid>8743502d-c0ba-4b90-a563-ec206a533469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::a[1]</value>
      <webElementGuid>4dca80d0-9d20-4465-b4e3-b5cb4712c5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Preview'])[1]/preceding::a[1]</value>
      <webElementGuid>5e54a35f-c433-40af-b48f-f84412265e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thống kê Email'])[1]/preceding::a[1]</value>
      <webElementGuid>aa330aa0-4d70-4ddc-9aab-3040ee14fed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Performance Analyzer']/parent::*</value>
      <webElementGuid>8440a01c-eee2-4fee-818e-480771f58e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/CamNest/admin/emailPerformance']</value>
      <webElementGuid>5aca2fda-e705-47a7-acd9-e996af38fc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>eb55f1c4-6c09-4d66-940d-f922a718b6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/CamNest/admin/emailPerformance' and (text() = '
                 Performance Analyzer
              ' or . = '
                 Performance Analyzer
              ')]</value>
      <webElementGuid>5994b995-617a-4d90-a98b-aec7c65a1352</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
