<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Subscribe for news_signupButton (8)</name>
   <tag></tag>
   <elementGuidId>4424a3a2-7e56-450c-b1a2-d07cf72010f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signupButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='signupButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbc82cfb-ef81-4155-ac10-5c2c9a79aea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7fea8007-970c-4c01-8e1a-261c0f0c54c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signupButton</value>
      <webElementGuid>fa496be5-e168-47aa-a81e-8756432d8630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up</value>
      <webElementGuid>91a4d107-8ec1-4ada-b8e6-5095528dd825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupButton&quot;)</value>
      <webElementGuid>c2da43ce-cd3c-4873-ba0b-2de5f6cc35a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='signupButton']</value>
      <webElementGuid>84439312-4a8c-4c61-a922-812ea6fceaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/button</value>
      <webElementGuid>45fe8276-3a05-4eea-9689-c67013aa42fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe for news!'])[1]/following::button[1]</value>
      <webElementGuid>3042525c-bf21-4d87-abbf-8a50672b23c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I have read and accept EULA'])[1]/following::button[1]</value>
      <webElementGuid>3d330b2b-1bee-405a-9bc3-d00efa865359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or'])[2]/preceding::button[1]</value>
      <webElementGuid>0bbfb402-2591-4bd0-8b18-d4b07d42f7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::button[1]</value>
      <webElementGuid>8ffb414b-18b8-4b97-b43d-c2844709c362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/button</value>
      <webElementGuid>5476b127-64d9-4f5d-8ff3-ebd431466bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'signupButton' and (text() = 'Sign Up' or . = 'Sign Up')]</value>
      <webElementGuid>0129c623-b44f-4c2c-b814-543f35d4afba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
