<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Or_alert-danger (1)</name>
   <tag></tag>
   <elementGuidId>ca5c7fad-b041-4717-b02b-e745a0b00315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.alert-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='signupForm']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aaad55fe-fb01-4b41-b570-3df82d347876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert-danger</value>
      <webElementGuid>d75953be-25cb-477b-a204-ea31771dbb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mật khẩu xác nhận không khớp!</value>
      <webElementGuid>2a99ef2f-46e4-4771-803e-09786d154be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupForm&quot;)/div[@class=&quot;alert-danger&quot;]</value>
      <webElementGuid>db4be5ab-f29b-4f6c-ad93-e765f2332111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div</value>
      <webElementGuid>472a8b3f-8a4e-4c35-b512-34c8f0785789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or'])[1]/following::div[4]</value>
      <webElementGuid>1439e446-501c-4e8e-9d0c-797b5f249760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::div[8]</value>
      <webElementGuid>125bd312-a5f2-4110-9a19-5767c67f8c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::div[1]</value>
      <webElementGuid>40abc3a2-c2fc-4f53-bb73-b6bc6c78e957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🙈'])[2]/preceding::div[1]</value>
      <webElementGuid>bbcbe3ed-c0e5-4a0b-9b07-521c84107e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mật khẩu xác nhận không khớp!']/parent::*</value>
      <webElementGuid>38588869-2dae-43e4-9439-dee4eac6332d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div</value>
      <webElementGuid>9b0e8ddf-3759-471f-9dd8-6751077c4717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Mật khẩu xác nhận không khớp!' or . = 'Mật khẩu xác nhận không khớp!')]</value>
      <webElementGuid>d4e85bbb-81f1-436e-895f-7daaabc938fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
