<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Contact_fas fa-user (4)</name>
   <tag></tag>
   <elementGuidId>134c4d70-f430-4ef3-9e48-dae7d1c5ad73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='login-icon']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>50f53313-72e1-4bdd-941c-316f0087043a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-user</value>
      <webElementGuid>8a130c93-7384-4108-8ed3-0257d38b87f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-icon&quot;)/a[1]/i[@class=&quot;fas fa-user&quot;]</value>
      <webElementGuid>6d9812b6-c961-4e4e-b1f7-0da7cdf90cae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='login-icon']/a/i</value>
      <webElementGuid>17c11667-34db-4351-a4a9-973283920a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/i</value>
      <webElementGuid>03ffc63f-229a-46f2-b88e-a1a6cbca1584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
