<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Contact_fas fa-user (55)</name>
   <tag></tag>
   <elementGuidId>54639894-06a0-48ed-a42c-407cf5a1abf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='login-icon']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6d6c03ab-57e7-4e68-bf8a-3c464f5c9e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-user</value>
      <webElementGuid>9e2b12a3-0e52-4f56-99f2-9ce64ff108e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-icon&quot;)/a[1]/i[@class=&quot;fas fa-user&quot;]</value>
      <webElementGuid>018cd156-e704-44b9-8800-481c415126fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='login-icon']/a/i</value>
      <webElementGuid>44fc3749-0f03-45b2-b2b8-c902e886cc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/i</value>
      <webElementGuid>7e71e1db-3156-4cc8-86ac-1e36a4550ac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
