<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Contact_fas fa-user (23)</name>
   <tag></tag>
   <elementGuidId>892e5498-46cb-4925-8922-1399dd1c28be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='login-icon']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5f040c01-6fe8-4a1a-85bb-25274ab0d172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-user</value>
      <webElementGuid>a30722c5-fa68-4913-8803-154fefc1c2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-icon&quot;)/a[1]/i[@class=&quot;fas fa-user&quot;]</value>
      <webElementGuid>1a798539-2338-43af-91fa-a45c1c7dc374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='login-icon']/a/i</value>
      <webElementGuid>2c59a626-0071-4c68-9f46-eddcaaadd043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/i</value>
      <webElementGuid>be254735-3274-4943-90e0-c396c90b8ebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
