<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Email Preview_email-preview</name>
   <tag></tag>
   <elementGuidId>82240fcc-688f-4efd-bbde-e58904e6e1ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='email-preview']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email-preview</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ed2d4e86-4ea9-4770-8363-812569d18e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-preview</value>
      <webElementGuid>76d5eeff-78ca-4658-8b49-d57962e6ff6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcdoc</name>
      <type>Main</type>
      <value>&lt;p style='color:gray;text-align:center;padding:1em;'>Vui lòng chọn template để xem trước&lt;/p></value>
      <webElementGuid>2b9bbd87-2201-4cd5-8bc8-1f70354d8e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-preview&quot;)</value>
      <webElementGuid>c41d3bb8-fd73-49e4-b3ee-d53e08268248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='email-preview']</value>
      <webElementGuid>cf6e6a1a-08ec-41cb-8e60-3767df92989e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='preview-content']/iframe</value>
      <webElementGuid>1337f2e8-af59-4036-8370-8f503b76958f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c6c378db-4bcb-4392-9021-5487e79f151c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'email-preview']</value>
      <webElementGuid>945a186e-de54-41c8-b0ce-bfc1aec43c13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
