<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Target_all (2)</name>
   <tag></tag>
   <elementGuidId>452fd16a-2602-4deb-a2f9-0361c7f2d7a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#all</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='all']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2781a862-ff24-4ab9-a930-8654dc124a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>08f6d4a3-2811-42c4-98d8-9186f0e3019b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>all</value>
      <webElementGuid>38225f84-8570-4a6a-be6c-6eee056a3720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>all-subscriber</value>
      <webElementGuid>619e1af7-a2d2-41cf-b7d7-e457b129132d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;all&quot;)</value>
      <webElementGuid>79067a60-45ed-4bff-b386-be8ec43dc771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='all']</value>
      <webElementGuid>40de822f-9a3f-405f-95e8-d53b8745cd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-1']/div/div/input</value>
      <webElementGuid>576712f0-8f7d-4599-ab3d-67a9ad8f7992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>39244713-2a03-4720-babb-a40a07c82426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'all' and @name = 'all-subscriber']</value>
      <webElementGuid>5d6b6a29-b4b9-48cd-ab47-3e618c4e270a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
