<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__signupPassword2 (4)</name>
   <tag></tag>
   <elementGuidId>54da4dff-c639-494d-a36e-aa0c73526022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signupPassword2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signupPassword2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>455d7e8a-27f5-4508-beac-11b25e793ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fe60afe1-8e57-4a8f-bbf1-003c6b56eddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signupPassword2</value>
      <webElementGuid>15d063e5-5133-45e9-98da-ebc67b8796e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm-password-signup</value>
      <webElementGuid>64058264-52d9-4bd7-b8c4-f21e435a3e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>f558f6ab-ad85-4cdd-bda6-066df220e897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupPassword2&quot;)</value>
      <webElementGuid>b1611d62-e024-4631-85a5-e58eadabf67d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signupPassword2']</value>
      <webElementGuid>7679fe01-ff8b-4a57-ae7a-d42b0f99936a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[2]/input</value>
      <webElementGuid>69fa59ab-304b-4044-a035-f4b8e578a62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/input</value>
      <webElementGuid>6c98c682-17af-4aae-9606-99d8673ee6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'signupPassword2' and @name = 'confirm-password-signup' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>f7c09b3f-167e-4f9a-9a13-9e7b13e8ab44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
