<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__signupPassword2 (5)</name>
   <tag></tag>
   <elementGuidId>ef8a73a9-a36e-42a8-91bd-c5efc1ff7f0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signupPassword2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signupPassword2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>926885b8-6196-45be-bdc6-159c93efeae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cd9f2cd6-fe49-4bec-90fe-19a80abc960f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signupPassword2</value>
      <webElementGuid>3cb009a4-6fab-49ad-832e-29b40e61caa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm-password-signup</value>
      <webElementGuid>bc67d9c6-4250-4d2b-8107-451e7ba5583d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>3359fc4c-8a82-4aad-9106-ba98e63cf688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupPassword2&quot;)</value>
      <webElementGuid>866e5a37-dccb-47b2-b547-217d1914b1c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signupPassword2']</value>
      <webElementGuid>2fcfbb57-98e6-4b4c-b563-1868c1160999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[2]/input</value>
      <webElementGuid>c0a70048-36b2-4569-882c-5edf8c2cc1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/input</value>
      <webElementGuid>1ddc360c-40d2-4ea3-ad3d-0176a9463343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'signupPassword2' and @name = 'confirm-password-signup' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>405c1951-e3b1-4fd3-8f9a-dfd007282964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
