<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact_loginPassword (47)</name>
   <tag></tag>
   <elementGuidId>f4db1abd-cd14-4f04-874a-5757d8b5dead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f31c8b0-6b8e-4e36-a2ac-5757c7e1e2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>db49fa37-4202-4bf6-8ca3-8691843104ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginPassword</value>
      <webElementGuid>7fc3336c-5d15-4365-91d8-5f2cc3544c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b4366dfa-e8d6-41dc-8528-22c826971761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>1eeb61a3-8a4c-4f99-b553-62a012946b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginPassword&quot;)</value>
      <webElementGuid>f0880771-b75e-47b5-8e80-111927fa5de4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginPassword']</value>
      <webElementGuid>b1ea19e8-a426-4bbc-86d5-f202d07330ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginPopup']/div/div/form/div/input</value>
      <webElementGuid>08e9b392-e798-4183-8918-c3ca04467f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>bf62d7f3-b361-48ea-aa71-3167a85cb606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'loginPassword' and @name = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>f068cda3-7c82-4c9c-90b2-d9839774ae00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
