<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Target_all (1)</name>
   <tag></tag>
   <elementGuidId>7c345b15-c226-49a8-91e3-1718a7943123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#all</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='all']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9dd1e248-8311-4b35-b0bc-388e8cae602f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>14a636ad-5b3b-4bd4-8f51-36974ba8e355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>all</value>
      <webElementGuid>f054eb14-31b5-4a67-baa2-d71e48cdc67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>all-subscriber</value>
      <webElementGuid>76e6cb0b-f26b-474a-99e6-1efbb224f95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;all&quot;)</value>
      <webElementGuid>17beda7b-07eb-4476-838c-7c873810a2cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='all']</value>
      <webElementGuid>3ec688ce-4c3a-4368-a9c1-ee7abb4f8814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-1']/div/div/input</value>
      <webElementGuid>d668140f-a4ca-4d1b-9c71-7ea5fb002f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>e07f9f8b-2b8c-4388-a1d0-5690d3b25b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'all' and @name = 'all-subscriber']</value>
      <webElementGuid>155c0807-d74b-4bcb-89f5-9f2b7d820a93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
