<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__acceptEULA (1)</name>
   <tag></tag>
   <elementGuidId>fdff7bf1-57b8-44e1-b5bb-bd251240c6ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptEULA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acceptEULA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68445e7e-b039-4a8b-bffd-34f0b22dc6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7c783ba3-57f3-40b5-8400-f5ed05ca483e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptEULA</value>
      <webElementGuid>e7502fee-cdb5-46ac-9d23-26b39aad5666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acceptEULA</value>
      <webElementGuid>b1ade67c-2edc-4114-b325-550d0c80f81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptEULA&quot;)</value>
      <webElementGuid>f50f0c3c-cc2d-43ae-88da-cbc366bf1e67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acceptEULA']</value>
      <webElementGuid>7512c7b5-26f9-4798-8894-82189140ed19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[3]/input</value>
      <webElementGuid>c7f093a8-086d-4d11-879b-bd5aad39c3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>70cce3d6-f507-450b-b91e-e5370232975b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'acceptEULA' and @name = 'acceptEULA']</value>
      <webElementGuid>93ba679d-ba9a-4b88-8ff7-b0ecd63a9454</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
