<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__signupPassword2 (1)</name>
   <tag></tag>
   <elementGuidId>b973fd99-5213-43b4-a8da-9f10d0944905</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signupPassword2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signupPassword2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0c18fa0-4b43-4237-acb7-3e4058db7b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d790c504-bb85-4bca-a012-d5ecd1b47fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signupPassword2</value>
      <webElementGuid>56d6cdd8-9ceb-4150-bc49-92d00b753333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm-password-signup</value>
      <webElementGuid>5d55a6fb-c6d9-492e-a794-ca1376c9d0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>c5890247-6ebd-4e24-b409-178f0ea58829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupPassword2&quot;)</value>
      <webElementGuid>63c12d7e-0f99-4827-ada7-0234fa229195</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signupPassword2']</value>
      <webElementGuid>ace21f7e-2c63-410b-847b-fb5fd0591a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[2]/input</value>
      <webElementGuid>38755f45-49d7-4d9d-9e93-4673e3488c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/input</value>
      <webElementGuid>83bda497-0408-4d3a-9480-5d4cba1fbd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'signupPassword2' and @name = 'confirm-password-signup' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>8c1383f1-7f47-4ffb-8e55-e8149b75beb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
