<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign Up_signupPassword1 (6)</name>
   <tag></tag>
   <elementGuidId>9e86bbc9-4c37-4ad2-82b8-c2dbdc4d2e57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signupPassword1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signupPassword1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>315fa8f7-c05e-424b-8514-ca3ef2d3dbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>54001bed-8146-423e-91fa-ac2893122278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signupPassword1</value>
      <webElementGuid>8dd1a059-3157-49f9-bd7e-8aee0b84dd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>03d7721c-48a8-4046-b877-76977de80008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>1d66f13e-4728-4fcc-b6a1-1a6c6b2aad87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupPassword1&quot;)</value>
      <webElementGuid>34ef1e9f-4c7a-47af-96e7-fb0a2c11d699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signupPassword1']</value>
      <webElementGuid>f62d28cf-2210-4751-80a8-5a10c0630b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div/input</value>
      <webElementGuid>94d7bb10-eb93-4591-adce-bed5295b0b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/input</value>
      <webElementGuid>b8bae42a-a65a-48f3-85c5-2f47b0d7e111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'signupPassword1' and @name = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>93bbde41-9736-4067-bf4e-2687a479bd44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
