<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign Up_txt-signup (1)</name>
   <tag></tag>
   <elementGuidId>750790d2-ff6e-4213-ad4a-953c70b2861f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txt-signup&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txt-signup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fc89b49-f39b-4e58-a832-671dd4be34a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>730e5fb4-ed61-4025-95d2-f5cf04ad6e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt-signup</value>
      <webElementGuid>b0689925-b34f-4b69-aecc-3b384b827363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User name</value>
      <webElementGuid>d638c1a3-1568-425c-85d3-926c499af538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupForm&quot;)/input[1]</value>
      <webElementGuid>1f409861-a3cf-430e-b2a7-c38ae5fb1264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txt-signup']</value>
      <webElementGuid>7eb98827-9d06-4072-ba30-21e47035a75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/input</value>
      <webElementGuid>3e5f0c14-1911-4d5e-b2d0-7016921d0589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/input</value>
      <webElementGuid>c5fd2768-befc-4ea4-b53b-3900a242d59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt-signup' and @placeholder = 'User name']</value>
      <webElementGuid>f9d43a54-52ee-441a-9e31-69de5b992cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
