<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tm kim email_search-email (1)</name>
   <tag></tag>
   <elementGuidId>a9293872-6a87-46a7-b08c-43ac154758f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d995943c-9eb2-4170-97d0-1d8ee70c0665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4f6fa22-5192-40a9-b07c-604358266618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-email</value>
      <webElementGuid>d108fe61-c230-4f6a-8469-6bab2c578a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập email...</value>
      <webElementGuid>fb3b53b5-e89d-4b0d-989b-15341d433c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-email&quot;)</value>
      <webElementGuid>2e478ad8-917b-4c45-a98b-9bd21581cff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-email']</value>
      <webElementGuid>a023c762-24d0-4cf5-ac08-d6b95f543f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search-form']/div/input</value>
      <webElementGuid>ead154bc-c3fb-4db4-b81d-4d406251b065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/form/div/input</value>
      <webElementGuid>fe69084b-6bba-4993-91f9-b4a87fa04c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'search-email' and @placeholder = 'Nhập email...']</value>
      <webElementGuid>40d2d5d6-97ae-4f48-ae40-b2b84867d4fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
