<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__acceptEULA (6)</name>
   <tag></tag>
   <elementGuidId>6e5acf59-6fa8-4e7e-bbff-6270f1fb9873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptEULA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acceptEULA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60b0ad73-1407-4e61-9adb-808ac6b2acd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>279899b3-b144-4e03-b9b4-0f87beac812a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptEULA</value>
      <webElementGuid>2572fc9d-14aa-42ee-b7ec-fd919ee71853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acceptEULA</value>
      <webElementGuid>ee8140be-887e-4abf-a18a-3116599b2bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptEULA&quot;)</value>
      <webElementGuid>3b5ad2e8-5730-4c7e-9129-ec0eaae21d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acceptEULA']</value>
      <webElementGuid>e21d13f3-bc11-4d9a-8f60-12f3bdda85b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[3]/input</value>
      <webElementGuid>2ebe3a43-ac1d-4e74-b9aa-6d8bd073cd8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>6fc2e5bd-1adc-4e46-949a-612f93f284b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'acceptEULA' and @name = 'acceptEULA']</value>
      <webElementGuid>9d48b642-d936-4468-b001-fabd52b8c987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
