<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__signupPassword2 (8)</name>
   <tag></tag>
   <elementGuidId>df2a1e2f-1628-4413-b451-fb22c4a09d0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signupPassword2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signupPassword2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9678f618-8ec3-48b1-8d7c-7eac0e5065db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>18e36129-a012-47ba-8b9f-46b7fc8d927f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signupPassword2</value>
      <webElementGuid>f515e106-4406-418c-9126-2eace78fb44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm-password-signup</value>
      <webElementGuid>72607348-a3c8-47d9-899f-b60971793e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>b7a23ea9-a50e-45ad-bbf2-28f3756f3be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupPassword2&quot;)</value>
      <webElementGuid>e358018b-2a6f-47c3-9512-1f4a435e7d12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signupPassword2']</value>
      <webElementGuid>9e275b2b-89bb-4153-b69c-ae8bdc1669f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[2]/input</value>
      <webElementGuid>8967124e-016b-43ad-982c-888ac0d34348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/input</value>
      <webElementGuid>f3dfc668-39c1-42f3-8fd8-e1bdc9d43481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'signupPassword2' and @name = 'confirm-password-signup' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>29c96613-47c1-42c2-bd33-544f9b868f83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
