<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__acceptEULA (2)</name>
   <tag></tag>
   <elementGuidId>1671f9b5-d72b-4449-b2a7-8026aa9db98d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptEULA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acceptEULA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0667a28-3c8b-4add-8bcf-8049d4137b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>70122c16-f414-4519-a25b-287d0a9dad21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptEULA</value>
      <webElementGuid>f4a3446c-352e-4134-8ba5-32675837510b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acceptEULA</value>
      <webElementGuid>8d437c1e-91bf-4f37-b04b-a66be495f061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptEULA&quot;)</value>
      <webElementGuid>e81d90be-c1cf-44b1-a1b2-1c177b63ef7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acceptEULA']</value>
      <webElementGuid>7351a277-6d0c-433e-b814-b008396a2b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[3]/input</value>
      <webElementGuid>f7c693f5-6135-4ccb-a70d-b9bdcb64439c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>098ce97e-bd74-4f22-8799-b36561285e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'acceptEULA' and @name = 'acceptEULA']</value>
      <webElementGuid>da00e275-6905-4d5f-9d19-9fe4577b3987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
