<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact_loginPassword (48)</name>
   <tag></tag>
   <elementGuidId>561ea33b-3c33-4d5d-881b-10d13006b42a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10993f7e-a345-4869-9ba4-40ee87e4f973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b2207a64-2c27-44a1-b736-5189c109a873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginPassword</value>
      <webElementGuid>0732fc4f-f3fa-4c63-a0f5-d25ccb6c07a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a399bdc6-0249-4857-b8d3-6ed800103e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>c3b8f4d6-41f2-4621-a144-519c3ef4d6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginPassword&quot;)</value>
      <webElementGuid>9cdc6902-1fa1-4607-82ee-3d16d08cc572</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginPassword']</value>
      <webElementGuid>b553b533-4832-4e37-87d5-457678632127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginPopup']/div/div/form/div/input</value>
      <webElementGuid>fb172763-5369-482b-ba3a-8d19f2ad66b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>f11665ab-b1ac-4b37-884d-4a1b642b7800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'loginPassword' and @name = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>5a50f9f3-9e2f-435a-a663-c73ebf62809e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
