<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__acceptEULA (3)</name>
   <tag></tag>
   <elementGuidId>df9ab4b6-2cda-4e72-8fa4-d94e10453471</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptEULA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acceptEULA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0e79c41-674d-4392-aaf4-4a590bebc9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9e04a957-c83a-40d6-a8b5-95bbef370b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptEULA</value>
      <webElementGuid>8fe65219-3dd3-49d2-a5c0-a5ed36998343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acceptEULA</value>
      <webElementGuid>38a66e6d-c7de-464b-945b-43cfd1881acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptEULA&quot;)</value>
      <webElementGuid>2918fc4b-dc0f-46eb-9e18-1a19a90601d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acceptEULA']</value>
      <webElementGuid>3684232c-8675-4ace-8743-073e54c726fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[3]/input</value>
      <webElementGuid>da520069-c1c8-451d-a64f-76989eca5ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>82a84cf3-8dbc-47ac-873b-b45c130bfba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'acceptEULA' and @name = 'acceptEULA']</value>
      <webElementGuid>1a6fabaa-6317-4536-b92f-5469456e60c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
