<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact_loginPassword (53)</name>
   <tag></tag>
   <elementGuidId>080fcab9-2657-4527-80e8-f9989984bda0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08b4420d-47fc-4287-b39f-3b2eaed0af74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>92a176c5-c6bc-4ff2-9ba9-29794595bc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginPassword</value>
      <webElementGuid>9560f05b-0af8-4c02-978a-e8bf40a4e1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e9b009b4-ac68-4fb2-911b-4b99cf1a2626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>6a6e76d0-269a-4a97-a6d7-71b3bb459150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginPassword&quot;)</value>
      <webElementGuid>0ebe91b6-780c-4c1b-bdf6-e5f7b46cbb99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginPassword']</value>
      <webElementGuid>77159a15-d4d7-4320-8423-ddf405b64d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginPopup']/div/div/form/div/input</value>
      <webElementGuid>8f23a0b3-2b52-4265-a6c1-40d34510be05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>19747af5-36be-4ab8-a401-49f9ccb4dea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'loginPassword' and @name = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>787123a2-de05-4dbd-921a-fb7655111cdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
