<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Or_toggleLabel (9)</name>
   <tag></tag>
   <elementGuidId>2eaeda8b-b17f-4f99-8beb-ac5ad46d67d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toggleLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='toggleLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f54ed4c2-0945-4f97-be84-92064f137c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>116350fe-d895-41ad-b22e-f930020652b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>94cf383b-8952-4a6b-b7b7-4dd7ffa9e69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggleLabel</value>
      <webElementGuid>b7da3f16-4502-48ba-9c1e-76f11a6d0c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggleLabel&quot;)</value>
      <webElementGuid>5daae386-104a-4a49-8183-6adc56c400fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='toggleLabel']</value>
      <webElementGuid>e9d3a2f7-a4ca-4e14-8a71-2acc1ada7336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/label</value>
      <webElementGuid>61971007-0fee-4a3d-a0f4-4eae56faf47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/label</value>
      <webElementGuid>812847e1-ad3a-4ee4-920f-76f4427aa64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'toggleLabel']</value>
      <webElementGuid>c31f49f2-96eb-44ca-8fb0-61ab05d6a760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
