<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_I have read and accept EULA_subscribeLabel</name>
   <tag></tag>
   <elementGuidId>a42b5789-bfb5-4a6b-a08d-93c5e6081174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='subscribeLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subscribeLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e2dfde2d-88d1-46cc-b025-e66f3ff4f28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>subscribeNews</value>
      <webElementGuid>853a0dbb-9248-417a-bf3d-e3d224b78e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-label</value>
      <webElementGuid>5d689c33-3a98-411a-b79b-a280db5da929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subscribeLabel</value>
      <webElementGuid>6fd07bef-ec94-4784-8abc-aa82fe1665d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribe for news!</value>
      <webElementGuid>7c9594d3-0053-4140-97cd-e22a3400deac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subscribeLabel&quot;)</value>
      <webElementGuid>532cf017-6f6d-447a-abe2-feee097bac4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='subscribeLabel']</value>
      <webElementGuid>b8bd24b2-c186-4c6a-b115-9377a8747e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[4]/label</value>
      <webElementGuid>0dbb23b7-a17d-4bde-9f46-d4cf1498e167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I have read and accept EULA'])[1]/following::label[1]</value>
      <webElementGuid>29bddf9e-6807-441a-8ada-ef426b878265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🙈'])[3]/following::label[2]</value>
      <webElementGuid>780007b8-bee8-4300-a782-bacaddd4fad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[2]/preceding::label[1]</value>
      <webElementGuid>f4c370b6-0006-4568-9c2e-b2e178b23d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or'])[2]/preceding::label[1]</value>
      <webElementGuid>7b50cb85-0819-4490-8807-20cb245aec41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subscribe for news!']/parent::*</value>
      <webElementGuid>a3eabf55-2cfc-4275-8f2e-239eee2c0f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label</value>
      <webElementGuid>cc54a06a-75dc-4162-89e0-2782084ba11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'subscribeLabel' and (text() = 'Subscribe for news!' or . = 'Subscribe for news!')]</value>
      <webElementGuid>c0d2b9ed-7b8a-4af5-acb5-783d36465156</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
