<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Or_toggleLabel (7)</name>
   <tag></tag>
   <elementGuidId>00516fb2-c47c-4f23-b3cc-870b36babfe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toggleLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='toggleLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0ce3f4b2-109e-411e-9570-2ab8c1ce5aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>af4c35d5-7e85-4615-a132-8e728036e833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>158a4e21-fb55-462e-9b5d-2e5027d7bda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggleLabel</value>
      <webElementGuid>cf5b5c3f-15e9-471a-8344-3f62cb94ec01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggleLabel&quot;)</value>
      <webElementGuid>1e490fd1-8555-4f4b-9c98-8ff99c7d617c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='toggleLabel']</value>
      <webElementGuid>4825a2e2-cb7a-4180-b2f8-c2f6fc729ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/label</value>
      <webElementGuid>f8286c39-06c9-41ff-b907-791a3d9ff48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/label</value>
      <webElementGuid>6c93acf9-fb33-4f62-a1af-b5005c11d4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'toggleLabel']</value>
      <webElementGuid>bb2f790e-72eb-4f14-8571-1daa93316052</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
