<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Or_toggleLabel (12)</name>
   <tag></tag>
   <elementGuidId>7f9d934b-b305-4c51-8211-be31c1f38e10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toggleLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='toggleLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>520cac4e-0990-4a6a-9e6e-72b946f302c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>978d847c-1348-421e-9945-b26e6e7b8ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f57beee8-3df1-4da2-a82d-a5a0dbade5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggleLabel</value>
      <webElementGuid>78655f3e-6fd1-4a1e-8653-045bc1167af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggleLabel&quot;)</value>
      <webElementGuid>694ae21d-8470-410f-b6f2-1cb92143a754</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='toggleLabel']</value>
      <webElementGuid>c19f6b07-dd7e-4bce-b837-f84b3ee4b886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/label</value>
      <webElementGuid>28b6ded8-f5c7-4b56-885b-c455bfc4a2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/label</value>
      <webElementGuid>063b73e8-f580-4ada-9d35-6b76318217b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'toggleLabel']</value>
      <webElementGuid>fe1a4d0b-780f-4313-90ef-3e8e9db18a74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
