<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Or_toggleLabel (5)</name>
   <tag></tag>
   <elementGuidId>0d7bbeef-155c-4117-9650-e27bdff6cab1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toggleLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='toggleLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3ab83208-859e-4b14-aa59-19625a5f7514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>fe58f518-a41a-4fc6-a4fe-b614e1e60093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a9ba6206-0d6c-4c2f-b256-187adfd14f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggleLabel</value>
      <webElementGuid>d223d019-3f01-4425-9f9a-30cf15a4db92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggleLabel&quot;)</value>
      <webElementGuid>2a62e23d-7db6-4caf-b1bf-2e064055a09f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='toggleLabel']</value>
      <webElementGuid>1ee05ad5-f80f-44a8-8c74-36da60776674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/label</value>
      <webElementGuid>0d57d24b-53a7-4d92-aeab-6bb468fb6cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/label</value>
      <webElementGuid>bbb5c84f-a812-4b8a-b71d-913d66024194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'toggleLabel']</value>
      <webElementGuid>44ea0b96-d3a7-4ea3-9703-ccd0f10e308f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
