<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Or_toggleLabel (11)</name>
   <tag></tag>
   <elementGuidId>5b5c7717-ce49-41ed-a87c-f191748ce7ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toggleLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='toggleLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>93714c38-1170-4bd8-b148-0dc7e2e4522f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>05f1c326-e93d-4491-bdea-c50aa65189f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e07adbb5-7467-4a62-95a5-661b717ce6b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggleLabel</value>
      <webElementGuid>ddc1e1cc-5cf5-42e3-a683-ba6e3e9ae227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggleLabel&quot;)</value>
      <webElementGuid>943039eb-86e1-4043-b3b3-7c0d19aeff89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='toggleLabel']</value>
      <webElementGuid>fe5eff72-b918-4944-bd16-d9854ecca145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/label</value>
      <webElementGuid>e6174b7d-31ba-4790-b6af-99f6091171fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/label</value>
      <webElementGuid>52b5fcf0-4ce6-4ca3-a223-bff787e0e0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'toggleLabel']</value>
      <webElementGuid>3068e2a9-9971-4458-9503-bdc3767d922e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
